### ISSUE TITLE
Bootstrap vs Materialize

### ISSUE THREAD

**Issue by fhunleth** [nerves-hub/nerveshub#67]
This issue tracks whether we'll use Bootstrap 3, 4 or Materialize for the initial web framework. While the UI should be straightforward, there is an expectation there will be enough client-side validation and and feedback that we might as well start with one.

**Comment by mobileoverlord** [comment]
I think that we should continue to use Bootstrap but upgrade to Bootstrap 4. We should investigate how we can do this with a minimum effort and impact, such as by pulling in minified CDN sources. We might have to introduce a JS build system to which I would suggest we configure webpack to pull the bootstrap source.

**Comment by fhunleth** [comment]
It sounded like people were fine with this direction. Nate mentioned looking into something. I don't have his Github ID at the moment to pull him in, but will try to get his 👍 .

**Comment by fhunleth** [comment]
@natestormer - Is Bootstrap 4 ok with you?

**Comment by natestormer** [comment]
@fhunleth I'm fine with using Bootstrap 4
